version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run: echo "npm installing backend & frontend"
      - run: npm --prefix backend install
      - run: npm --prefix frontend install
      - run: npm --prefix frontend run dev
